core:
  seed:
    alias: S
    type: int
    help: "Random seed (default: None)"
  episodes:
    alias: E
    type: int
    default: 2000
    help: "Number of episodes (default: 2000)"
  eval-timesteps:
    alias: V
    type: int
    default: 2000
    help: "Approximate number of timesteps during eval period (default: 2000)"
  eval-every:
    alias: EE
    type: int
    default: 100
    help: "Number of episodes between eval periods (default: 100)"
  discount:
    alias: D
    type: float
    default: .99
    help: "Discount factor (default: 0.99)"
  cheat:
    alias: C
    action: store_true
    help: "Whether to learn directly from hidden performance score (default: False)"
  log-dir:
    alias: L
    type: str
    help: "Subdirectory to write logs to for this run (defaults to combo of env, agent, cheating, mask, seed)"
